### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by biker8491** [alexh-name/bsec_bme680_linux#1]
I tried to compile your source code on a Raspberry Pi 3 and got the following error:
"/usr/bin/ld: cannot find -lalgobsec"

I used the following directories:

/home/pi/BME680 for your source code and
/home/pi/src/BSEC_1.4.5.1_Generic_Release_20171214 and
/home/pi/src/BME680_driver-master

What is wrong?

**Comment by alexh-name** [comment]
Apparently the lib search path in make.sh was incorrect. Fixed with 3241447e26cf352a139fcc6ab3e39c2a21d27e27. Could you check again?

**Comment by biker8491** [comment]
Ok. Now it compiles correctly!
