### ISSUE TITLE
Don‘t create bsec_iaq.state

### ISSUE THREAD

**Issue by Plastefuchs84** [alexh-name/bsec_bme680_linux#11]
Hello,
I have the problem that when completing the bsec_iaq.state is not generated. It should be created with or right? Completing with make.sh worked and the / bsec_bme680 outputs values.

In the make.config I had to adjust the directory BSEC_DIR accordingly.

pi@raspberrypi:~/bsec_bme680_linux $ ./make.sh
Compiling...
Compiled.
Copied config.

pi@raspberrypi:~/bsec_bme680_linux $ ./bsec_bme680
stat'ing binary file: No such file or directory
2018-08-15 23:03:54,[IAQ (0)]: 25.00,[T degC]: 24.83,[H %rH]: 48.86,[P hPa]: 1007.43,[G Ohms]: 77742,[S]: 0

pi@raspberrypi:/usr/src/BSEC_1.4.6.0_Generic_Release_20180425

I would be very happy about an answer. Unfortunately, I'm an absolute Linux beginner.

**Comment by alexh-name** [comment]
Hi,
the state file will be generated and filled the first time enough data was collected.
You can ignore the message.

However I made the messages clearer in bb50f6400ce62819ec62eb5d889ce01d588d45d6 and with 1a7aaf1 an empty state file will be generated for you.

So if you pull the update, all should be less confusing.
