### ISSUE TITLE
Humidity offset

### ISSUE THREAD

**Issue by ernesst** [alexh-name/bsec_bme680_linux#14]
In the file their is a way to apply an offset on the temperature, through
`#define temp_offset`
Is it possible to have the same to adjust humidity ? 

I'm looking at calibrating humidity level, to have better precision on the AIQ calculation.

**Comment by alexh-name** [comment]
AFAIK only offsetting temperature is intended, so you can compensate for the heat from surrounding electronics. The calculated humidity is impacted by the temp offset as well. You can compare calculated and raw humidity for more insight.
