### ISSUE TITLE
IAQ drifting up continuously?

### ISSUE THREAD

**Issue by geekything** [alexh-name/bsec_bme680_linux#15]
I've been running the code for the past few hours and now have an IAQ accuracy reading of "3". However, the IAQ value just keeps increasing and increasing -- I thought this was a percentage and it's now over 200?!

``2018-12-02 01:43:45,[IAQ (3)]: 232.51,[T degC]: 24.33,[H %rH]: 41.66,[P hPa]: 980.55,[G Ohms]: 127678,[S]: 0``
``2018-12-02 01:43:48,[IAQ (3)]: 232.82,[T degC]: 24.33,[H %rH]: 41.67,[P hPa]: 980.55,[G Ohms]: 128070,[S]: 0``
``2018-12-02 01:43:51,[IAQ (3)]: 231.89,[T degC]: 24.33,[H %rH]: 41.68,[P hPa]: 980.53,[G Ohms]: 128861,[S]: 0``
``2018-12-02 01:43:54,[IAQ (3)]: 232.54,[T degC]: 24.32,[H %rH]: 41.69,[P hPa]: 980.49,[G Ohms]: 127972,[S]: 0``
``2018-12-02 01:43:57,[IAQ (3)]: 231.13,[T degC]: 24.32,[H %rH]: 41.69,[P hPa]: 980.53,[G Ohms]: 129260,[S]: 0``
``2018-12-02 01:44:00,[IAQ (3)]: 230.87,[T degC]: 24.32,[H %rH]: 41.70,[P hPa]: 980.51,[G Ohms]: 128762,[S]: 0``

**Comment by alexh-name** [comment]
IAQ can have values between 0 and 500 and is not a percentage. [Check here](https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST-BME680-DS001-00.pdf) on page 9.

**Comment by geekything** [comment]
Thanks, I did eventually look at the datasheet :D

My upward drift has now stopped (burn in?). I still get relatively high IAQ readings (~100), but maybe that's my house and not the sensor!

Thanks for replying.

**Comment by alexh-name** [comment]
My readings too go easily above 100 without regular ventilation ;)
