### ISSUE TITLE
1.4.7.2 no compiling 'incompatible lalgobsec'

### ISSUE THREAD

**Issue by bsimmo** [alexh-name/bsec_bme680_linux#16]
I'm trying to compile this with the current **1.4.7.2** update.
I altered the address to new folder name.
Altered the _I2C_ address and the print output to a J_SON and added the new CO2 equivalent_ to the print output also.
Normal changes.  The last version I used was 1.4.6.#

I have set for Armv6 PiZero as I'm using 32bit RaspbianOS, SECONDARY I2C
I'm compiling this on RaspberryPi Desktop for x86, but that shouldn't be a problem, it'll then be moved over once compiled.
It fails with

`pi@PiLaptop:~/Desktop/BSEC Compile Zero/bsec_bme680_linux $ ./make.sh
Compiling...
/usr/bin/ld: skipping incompatible ./src/BSEC_1.4.7.2_Generic_Release_20190122/algo/bin/Normal_version/RaspberryPI/PiZero_ArmV6-32bits/libalgobsec.a when searching for -lalgobsec
/usr/bin/ld: cannot find -lalgobsec
collect2: error: ld returned 1 exit status
`

**Comment by alexh-name** [comment]
> I'm compiling this on RaspberryPi Desktop for x86, but that shouldn't be a problem, it'll then be moved over once compiled.

> `/usr/bin/ld: skipping incompatible`

Your linker is looking for libraries that match your architecture (x86) and fails because you point it to arm libraries. If you want to cross-compile for arm you need to set up your tool chain accordingly, it's not an issue with this project.

**Comment by bsimmo** [comment]
But I asked it to compile to RaspberryPi v6, does it not take care of
itself.

Anyway, there is a new version of bsec out to update too ;-)
And add the CO2 equivalents etc.

I guess I must have compiled it on the pi last time.
