### ISSUE TITLE
New versions

### ISSUE THREAD

**Issue by pwr33** [alexh-name/bsec_bme680_linux#2]
Hi, thanks for the example
FYI The latest BSEC library still has a bug reading high pressure but if you over write the files in the BSEC API directory with the latest BME680_driver files on github that issue is fixed
The latest BSEC adds another level to the include library path Normal/ 
and you have to copy bsec_datatypes.h and bsec_interface.h from /algo into /example to get it to compile

**Comment by pwr33** [comment]
yeah, it's a relative indicator, not a bad algorithm hidden away it seems.  after that post I deleted the ohms just dropped a bit and iaq up a lot, which when from your example you have 33 iaq at 500k resistance then 197 at 135000 is not unreasonable, but here it has not even seen 200k ohms yet and not much over that even outside.

**Comment by alexh-name** [comment]
Hi,
I will soon look into the new versions of the BSEC library and the BME680 driver, thanks for letting me know.

Regarding the accuracy of the IAQ ouput keep in mind that some burning in of the sensor is recommended (consult the documentation by Bosch), that it might need several days to fully calibrate to its typical surroundings and also that my implementation here just outputs the value calculated by the BSEC library to which this project has no influence of.
If there are doubts regarding the measured results you might better contact Bosch.

**Comment by pwr33** [comment]
I think it is just the poor air quality here, next to a main road and an industrial estate, plus like you say I think the BSEC algo probably needs a bit of time to observe a spectrum of high/low readings.

**Comment by alexh-name** [comment]
BTW I just updated the make script for the new version, see 1284880.
