### ISSUE TITLE
make does fail cause Bosch updated library to 1.4.8.0

### ISSUE THREAD

**Issue by c64emulator** [alexh-name/bsec_bme680_linux#21]
Hi,
thanx for sharing your efforts.
Currently migrating to a new RasPi4. Wanted to use the newest soft.

In the meantime BOSCH went forward with its library to version 1.4.8.0.

- Some files are on a different location:
  now: BSEC_1.4.8.0_Generic_Release/**examples/bsec_iot_example**/bme680.c
  now: BSEC_1.4.8.0_Generic_Release/examples/**bsec_iot_example**/bsec_integration.c
  now: BSEC_1.4.8.0_Generic_Release/examples/**bsec_iot_example**/bsec_integration.h

- ARCH does distinguish now between "PiThree_ArmV6" (32bit?) and  "PiThree_ArmV8" (64bit?) (directory is now "RaspberryP**i**")

Therefore the make.sh failes:
- patch does fail
- compile does fail

**Comment by c64emulator** [comment]
works now for me, with following changes:
- make.config:
```
BSEC_DIR='./src/BSEC_1.4.8.0_Generic_Release'
CONFIG_DIR='.'

VERSION='normal_version'

# Other architectures can be found in BSEC_DIR/algo/${VERSION}/bin/.
ARCH="${VERSION}/bin/RaspberryPi/PiThree_ArmV6"

# config for bme680, other configs are:
# generic_18v_300s_28d
# generic_18v_300s_4d
# generic_18v_3s_28d
# generic_18v_3s_4d
# generic_33v_300s_28d
# generic_33v_300s_4d
# generic_33v_3s_28d
# generic_33v_3s_4d
CONFIG='generic_33v_3s_4d'

```
- make.sh (snipped):
```
echo 'Patching...'
dir="${BSEC_DIR}/examples/bsec_iot_example"
patch='patches/eCO2+bVOCe.diff'
if patch -N --dry-run --silent -d "${dir}/" \
  < "${patch}" 2>/dev/null
then
  patch -d "${dir}/" < "${patch}"
else
  echo 'Already applied.'
fi

echo 'Compiling...'
cc -Wall -Wno-unused-but-set-variable -Wno-unused-variable -static \
  -std=c99 -pedantic \
  -iquote"${BSEC_DIR}"/API \
  -iquote"${BSEC_DIR}"/algo/${ARCH} \
  -iquote"${BSEC_DIR}"/examples/bsec_iot_example \
  "${BSEC_DIR}"/examples/bsec_iot_example/bme680.c \
  "${BSEC_DIR}"/examples/bsec_iot_example/bsec_integration.c \
  ./bsec_bme680.c \
  -L"${BSEC_DIR}"/algo/"${ARCH}" -lalgobsec \
  -lm -lrt \
  -o bsec_bme680
echo 'Compiled.'


```

**Comment by Gfast2** [comment]
Hi @c64emulator ,

Awesome stuff, I nearly got it to work on a Jetson Nano, but still got some minor issue drag me back. Any chance to post a full version of the make.sh mensioned above?

**Comment by alexh-name** [comment]
Done in 9cf11ed189136bb83a968211de9fea561478f76b.
