### ISSUE TITLE
README should be added more info?

### ISSUE THREAD

**Issue by mbechc** [alexh-name/bsec_bme680_linux#25]
I have a clean Rasbian - My Hardware is BME680 Breakout from Pimorino.

I had to run Pimorino installer before you're nice software worked

bme680@raspberrypi:~ $ curl https://get.pimoroni.com/bme680 | bash

Before this, the BME680 wasn't detected in I2C (lsmod | grep i2c) after the Pimorino instal,l the BME680 was detected and you're software worked perfectly - maybe som more intro to get the software running? - or did I miss you're docs?

**Comment by bsimmo** [comment]
The Pimoroni script probably enable I2C, which you'll not have done
You can do that in raspi-config manually
or
`sudo raspi-config nonint do_i2c 0`
I think.


It's probably not in the instructions (It isn't), as this is about compiling the BSEC and the python to read its output and not about getting it to work on a Pi.

But could be added? and also a bit on how to see which address it uses?


The Pimoroni script probably enable I2C, which you'll not have done
You can do that in raspi-config.

It's probably not in the instructions (It isn't) as this is about compiling the BSEC and the python to read its output and not about getting it to work on a Pi.

But could be added? and also a bit on how to see which address it uses?


Edit, it's also RaspberryPi OS not Raspbian _(with a p)_ 
The 32bit RPiOS is _based_ on Raspbian. But the 64bit is not, that's based on Debian.

**Comment by alexh-name** [comment]
I will add a section mentioning that I2C needs to be enabled.

**Comment by alexh-name** [comment]
Done in fec3d9e.
