### ISSUE TITLE
user_i2c_write: Remote I/O error

### ISSUE THREAD

**Issue by sarcoplasm68** [alexh-name/bsec_bme680_linux#27]
Hey,

excellent stuff, but I ran into the same problem as @Gfast2 in pull request #23. Except I spent an entire afternoon figuring it out myself, because I didn't look at the open pull requests. 
Opening a new issue for more visibility until merged or otherwise fixed. 

Thanks for sharing your work!

**Comment by ravisanapati** [comment]
hi, please check the i2c address in bme680.c check with both primary and secondary address
int i2c_address = BME680_I2C_ADDR_SECONDARY;

**Comment by alexh-name** [comment]
Thanks for feedback. I will add this in a FAQ section.
