### ISSUE TITLE
eCO2 always 0.00000000000

### ISSUE THREAD

**Issue by 4Heisenberg** [alexh-name/bsec_bme680_linux#30]
The value for eCO2 is always 0.0000000
The other values seem to look good.

When i run the make script I get an error related to eCO2

./make.sh: 25: cannot open patches/eCO2+bVOCe.diff: No such file

**Comment by alexh-name** [comment]
It seems like you are missing patches/eCO2+bVOCe.diff then, as in you have not downloaded this whole repo?
