### ISSUE TITLE
raspberrry pi 64 bsec library only actually furnished with BSEC_1.4.7.4 need a little port to work

### ISSUE THREAD

**Issue by maripo31** [alexh-name/bsec_bme680_linux#31]
bosch actually furnish only BSEC_1.4.7.4 version for raspberry native 64 bit raspian.
in this post :
https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/BME680-BSEC-Library-for-ARM64v8-elf64-littleaarch64/td-p/12977/page/2
You can get exemples and config directory from official bosch distro.
Your code do not download correctly the config file.
I workarround this point with using the static table furnished by bosch.
Replacing the config_load function by
  memcpy((void *)config_buffer,(void *)bsec_config_iaq,sizeof(bsec_config_iaq));
  return sizeof(bsec_config_iaq);
Where bsec_config_iaq are static data from bsec_serialized_configurations_iaq.c
make.sh must be adapted to add this file source.
You can close this point if bosch provide official version of raspberry pi 64 bits library.
Regards.

**Comment by alexh-name** [comment]
Since I don't own an arm64 platform to test on and 1.4.7 is outdated now, I will close this, but will link to your post in a FAQ section.
