### ISSUE TITLE
Sleep method in milliseconds

### ISSUE THREAD

**Issue by akirsch76** [alexh-name/bsec_bme680_linux#4]
Hello,

thank you very much for your work but I found an error in your code.

/*
 * System specific implementation of sleep function
 *
 * param[in]       t_ms    time in milliseconds
 *
 * return          none
 */
void _sleep(uint32_t t_ms)
{
  sleep(t_ms/1000);
}

This method does not sleep at all. If the software want so sleep for 25ms for example 25/1000 is 0. And the sleep function uses seconds. You should replace sleep with usleep in microseconds and multiply with 1000.
void _sleep(uint32_t t_ms)
{
  usleep(t_ms * 1000);
}

Kind regards

Alex

**Comment by alexh-name** [comment]
Wow thanks for pointing this out.
While your suggestion would work as well I took the opportunity to make it more POSIX compliant and used nanosleep: e6e6fb0

Best,
Alex

**Comment by akirsch76** [comment]
There are 1000 ways to rome ;-). But usleep() is also posix conform... ;-). But posix is somehow like SQL... Nice standard and a lot of implementation differences (my regular job)...

Best regards

Alex
