### ISSUE TITLE
BSEC_1.4.6.0_Generic_Release_20180409 incompatible // No bsec_integration.h file

### ISSUE THREAD

**Issue by mackowiakp** [alexh-name/bsec_bme680_linux#5]
just downloaded from Bosch site BSEC_1.4.6.0_Generic_Release_20180409.zip file, but it does not contain bsec_integration.h for any architecture. My project based on RPi 3B with Raspbian installed in it. Can anybody help me to find out fost file?

**Comment by alexh-name** [comment]
BSEC_1.4.6.0_Generic_Release_20180409 seems to be quite different from BSEC_1.4.6.0_Generic_Release_20180323 or older releases.
I will have to take some time digging into the changes. Hopefully soon.

I believe that unfortunately noone other then Bosch is allowed to give you the BSEC_1.4.6.0_Generic_Release_20180323, but maybe you could request it from them directly.

**Comment by alexh-name** [comment]
See https://github.com/BoschSensortec/BME680_driver/issues/25#issuecomment-383820475

**Comment by ferazambuja** [comment]
There is a bsec_integration.c file in /example, but probably is not the one you need.
Does this mean that the "script" is broken for now? I'm trying to use with my UnicornHAT HD :)

**Comment by pwr33** [comment]
All I needed to do was make sure the BSEC variable in make.config was pointing to right directory name and your example compiled and works OK, That was for latest BSEC downloaded today BSEC_1.4.6.0_Generic_Release_20180425 so could be a mistake bosch made in that previous release
They also seem to have updated the air pressure reading wrong problem in this release.

**Comment by alexh-name** [comment]
BSEC_1.4.6.0_Generic_Release_20180409 didn't include bsec_integration.c and the structure was quite different over all.
The current BSEC_1.4.6.0_Generic_Release_20180425 however follows the previously known structure and seems to be working just fine without any changes. I just updated the config to refer to the newest version. (93951debb6256a22147a047c14263beecf235954)

**Comment by alexh-name** [comment]
@ferazambuja 
I'm using a UnicornHAT HD too ;)

![img_2525](https://user-images.githubusercontent.com/1311361/39364527-8eadda22-4a2e-11e8-8605-83a4ece1450a.jpg)

**Comment by ferazambuja** [comment]
I will give it a try!
