### ISSUE TITLE
Air pressure issue

### ISSUE THREAD

**Issue by anttif** [alexh-name/bsec_bme680_linux#7]
Hi,

I have several Bosch BME 280's and they are reprting pressure more or less ~1012.7 hPa and BME 680 with this build reporting [P hPa]: 770.07. Local meteo is reporting 1018.3 hPa at their station. Is this some difference with HW?

**Comment by alexh-name** [comment]
Hi.

This project only implements the functions needed to start and loop the measurements by the sensor and the BSEC library and to read and output them. The results of the measurements should not be affected by anything in this project.
You might be better off asking your question at Bosch's repository: https://github.com/BoschSensortec/BME680_driver
I don't know anything about the BME280.

However I would start debugging by comparing the other values measured by your BME280 and BME680: Are temperature and humidity the same? Also check how the adjusted and raw values for temperature and humidity compare. You can get an output of the raw values by adding this line after line 200 in the bsec_bme680.c file:
`printf(",[raw T degC]: %.2f,[raw H %%rH]: %.2f", raw_temperature, raw_humidity);`
