### ISSUE TITLE
Cant run bsec_bme680

### ISSUE THREAD

**Issue by Jedimaster711** [alexh-name/bsec_bme680_linux#8]
every time I attempt to run my bsec_bme680 file, terminal closes instantly without any messages. I edited make.config so that the ARCH reflects the raspberry pi 3 instead of the zero since I'm using a pi3. not sure if I need to change the CONFIG path or not though. make.sh seems to work returning

Compiling...
Compiled.
Copied config.

------------------
(program exited with code: 0)
Press return to continue

no form of bsec_iaq.state is formed (unless its already somewhere else and I need to find it) although there is a bsec_iaq.config file formed by make.sh

**Comment by alexh-name** [comment]
Seems like compilation went fine, so your config and build environment should be ok.
How are you starting the compiled program?

**Comment by Jedimaster711** [comment]
was hitting "open in terminal" but just tried running it from terminal itself and got a "user_i2c_write: Remote I/O error" I have the BME680 plugged into pins 3-6 on the pi 3

**Comment by Jedimaster711** [comment]
RESOLVED: I went into bsec_bme680.c and changed line 34 from
int i2c_address = BME680_I2C_ADDR_PRIMARY;
to
int i2c_address = BME680_I2C_ADDR_SECONDARY;
I realised that the I2C was on 77 instead of 76

**Comment by ernesst** [comment]
Same issue with the standard Adafruit setup. Thanks !

**Comment by alexh-name** [comment]
How are you starting the program? Any error code? What is the return code?
Have you considered https://github.com/alexh-name/bsec_bme680_linux#troubleshooting?
